### ISSUE TITLE
Is the repo open for contribution?

### ISSUE THREAD

**Issue by hosszubalazs** [kukko/web-wombat#1]
Hey!

Thanks for the presentation yesterday, well done!

Are you accepting PRs?
What is the style you are using for commits? I'm not yet familiar with the tags used: fix/enhancement/progress.

Cheers,
Balázs

**Comment by kukko** [comment]
Hello!

Thanks for your attendance yesterday!

Yeah, I tottally accept PRs. In th beginning, I would merge pull requests, which is not conflicting with my future plans, about this repo. So If you want to make a feature, please contact with me, to prevent needless coding, which will not be merged into the main repo.

Keep coding!

Your sincerely, kukko.

**Comment by hosszubalazs** [comment]
Thanks for the answer! I opened a PR for some minor typo fixes, I was guessing that can go without a separate issue beforhand. Let's see how that goes. :) Closing this issue.
