### ISSUE TITLE
Specify language for README codeblocks

### ISSUE THREAD

**Issue by hosszubalazs** [kukko/web-wombat#3]
Specifying the language for the Markdown codeblocks would nicely highlight the syntax. For the Javascript code examples that would be a nice improvement.

Let me know if you agree, I can open a PR for this.

**Comment by kukko** [comment]
That was a great idea. I made this modification and commited it in the 53b08824ac9445680dbfb159ed8181bdcd4059ac commit. If you have further ideas to improve the README, let me know it, or you can open a pull request about it, and we will discuss it over there.
