### ISSUE TITLE
Improve headers in README

### ISSUE THREAD

**Issue by hosszubalazs** [kukko/web-wombat#6]
I checked the README with markdown lint ( plugin available in VS Code for example). It has a great bunch of rules: 
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

Something to consider is : "MD025 - Multiple top level headers in the same document" 

Currently all headers are top level. Based on this suggestion only the first one should be, the title row. All others should start from header level 2.

Functionality wise I think the current setup is fine. Stylistically I think it is an improvement, but this is quite subjective. Please consider. :)

**Comment by kukko** [comment]
Since you reported the comment, I updated the README and currently there are only one top level header and the others is header level two or three.
